version: 2.1
jobs: 
  build:
    docker:
      - image: circleci/node:1
    branches:
      only:
        - circleci-project-setup
    steps: 
      - add_ssh_keys:
          fingerprints:
            - "61:87:6b:06:38:bf:89:6f:33:f4:36:f3:c1:b3:35:1d"
      - checkout
      - run: 
        name: Install
        command: npm install
      - run: 
        name: Build
        command: npm run build